name: Build and Deploy Code

# Action(s) that triggers our workflow. "on" can be a list of actions [push, pull_request]
on: [push, pull_request]  # Here we are not specifying particular branches(s)

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo      # Step 1
        uses: actions/checkout@v4

      - name: Install python version 3.12   # Step 2
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: update pip    # Step 3
        run: python -m pip install --upgrade pip  # This is a linux shell

      - name: install all dependecies       # Step 4
        run: pip install -r requirements.txt

      - name: test with pytest    # Step 5
        run: |
          pip install pytest
          pytest
        # This is the actual command